### ISSUE TITLE
Build failed with typescript ^4.5

### ISSUE THREAD

**Issue by natsusola** [zWingz/vuex-ts-enhance#30]
build with typescript ^4.5
```
> vuex-ts-enhance@0.0.7 build /Users/natsu/test/vuex-ts-enhance
> tsc -p .

src/store.ts:63:43 - error TS2344: Type 'Getters<T>[Map[k]]' does not satisfy the constraint '(...args: any) => any'.
  Type 'Getters<T>[Map[keyof Map]]' is not assignable to type '(...args: any) => any'.
    Type 'Getters<T>[Map[string]] | Getters<T>[Map[number]] | Getters<T>[Map[symbol]]' is not assignable to type '(...args: any) => any'.
      Type 'Getters<T>[Map[string]]' is not assignable to type '(...args: any) => any'.
        Type 'Getters<T>[K]' is not assignable to type '(...args: any) => any'.
          Type 'Getters<T>[OnlyString<Getters<T>>]' is not assignable to type '(...args: any) => any'.
            Type 'Getters<T>[string]' is not assignable to type '(...args: any) => any'.

63   ): { [k in keyof Map]: () => ReturnType<Getters<T>[Map[k]]> };
                                             ~~~~~~~~~~~~~~~~~~

src/store.ts:68:38 - error TS2344: Type 'Getters<T>[k]' does not satisfy the constraint '(...args: any) => any'.
  Type 'Getters<T>[Keys]' is not assignable to type '(...args: any) => any'.
    Type 'Getters<T>[OnlyString<Getters<T>>]' is not assignable to type '(...args: any) => any'.

68   ): { [k in Keys]: () => ReturnType<Getters<T>[k]> };
                                        ~~~~~~~~~~~~~

src/store.ts:80:7 - error TS2344: Type 'GetNameSpaceObject<T, NameSpace, "getters">[Map[k]]' does not satisfy the constraint '(...args: any) => any'.
  Type 'GetNameSpaceObject<T, NameSpace, "getters">[Map[keyof Map]]' is not assignable to type '(...args: any) => any'.
    Type 'GetNameSpaceObject<T, NameSpace, "getters">[Map[string]] | GetNameSpaceObject<T, NameSpace, "getters">[Map[number]] | GetNameSpaceObject<...>[Map[symbol]]' is not assignable to type '(...args: any) => any'.
      Type 'GetNameSpaceObject<T, NameSpace, "getters">[Map[string]]' is not assignable to type '(...args: any) => any'.
        Type 'GetNameSpaceObject<T, NameSpace, "getters">[Keys]' is not assignable to type '(...args: any) => any'.
          Type 'GetNameSpaceObject<T, NameSpace, "getters">[GetNameSpaceKeys<T, NameSpace, "getters">]' is not assignable to type '(...args: any) => any'.
            Type 'GetNameSpaceObject<T, NameSpace, "getters">[GetNameSpaceKeys<T, OnlyString<Module<T>>, "getters">]' is not assignable to type '(...args: any) => any'.
              Type 'GetNameSpaceObject<T, NameSpace, "getters">[GetNameSpaceKeys<T, string, "getters">]' is not assignable to type '(...args: any) => any'.
                Type 'GetNameSpaceObject<T, NameSpace, "getters">["getters" extends OnlyString<Module<T>[keyof Module<T> & string]> ? OnlyString<...> : never]' is not assignable to type '(...args: any) => any'.
                  Type 'GetNameSpaceObject<T, NameSpace, "getters">[OnlyString<Module<T>[keyof Module<T> & string][keyof Module<T>[keyof Module<...> & string] & "getters"]>]' is not assignable to type '(...args: any) => any'.
                    Type 'GetNameSpaceObject<T, NameSpace, "getters">[string]' is not assignable to type '(...args: any) => any'.
                      Type 'GetNameSpaceObject<T, OnlyString<Module<T>>, "getters">[string]' is not assignable to type '(...args: any) => any'.
                        Type 'GetNameSpaceObject<T, string, "getters">[string]' is not assignable to type '(...args: any) => any'.
                          Type '("getters" extends OnlyString<Module<T>[keyof Module<T> & string]> ? Module<T>[keyof Module<T> & string][keyof Module<...>[keyof Module<...> & string] & "getters"] : never)[string]' is not assignable to type '(...args: any) => any'.
                            Type 'Module<T>[keyof Module<T> & string][keyof Module<T>[keyof Module<T> & string] & "getters"][string]' is not assignable to type '(...args: any) => any'.
                              Type 'Module<T>[keyof Module<T> & string]["getters"][string]' is not assignable to type '(...args: any) => any'.
                                Type 'Module<T>[string]["getters"][string]' is not assignable to type '(...args: any) => any'.

80       GetNameSpaceObject<T, NameSpace, 'getters'>[Map[k]]
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/store.ts:93:7 - error TS2344: Type 'GetNameSpaceObject<T, NameSpace, "getters">[K]' does not satisfy the constraint '(...args: any) => any'.
  Type 'GetNameSpaceObject<T, NameSpace, "getters">[Keys]' is not assignable to type '(...args: any) => any'.
    Type 'GetNameSpaceObject<T, NameSpace, "getters">[GetNameSpaceKeys<T, NameSpace, "getters">]' is not assignable to type '(...args: any) => any'.
      Type 'GetNameSpaceObject<T, NameSpace, "getters">[GetNameSpaceKeys<T, OnlyString<Module<T>>, "getters">]' is not assignable to type '(...args: any) => any'.
        Type 'GetNameSpaceObject<T, NameSpace, "getters">[GetNameSpaceKeys<T, string, "getters">]' is not assignable to type '(...args: any) => any'.
          Type 'GetNameSpaceObject<T, NameSpace, "getters">["getters" extends OnlyString<Module<T>[keyof Module<T> & string]> ? OnlyString<...> : never]' is not assignable to type '(...args: any) => any'.
            Type 'GetNameSpaceObject<T, NameSpace, "getters">[OnlyString<Module<T>[keyof Module<T> & string][keyof Module<T>[keyof Module<...> & string] & "getters"]>]' is not assignable to type '(...args: any) => any'.
              Type 'GetNameSpaceObject<T, NameSpace, "getters">[string]' is not assignable to type '(...args: any) => any'.
                Type 'GetNameSpaceObject<T, OnlyString<Module<T>>, "getters">[string]' is not assignable to type '(...args: any) => any'.

93       GetNameSpaceObject<T, NameSpace, 'getters'>[K]
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/store.ts:150:43 - error TS2344: Type 'Mutations<T>[Map[k]]' does not satisfy the constraint '(...args: any[]) => void'.
  Type 'Mutations<T>[Map[keyof Map]]' is not assignable to type '(...args: any[]) => void'.
    Type 'Mutations<T>[Map[string]] | Mutations<T>[Map[number]] | Mutations<T>[Map[symbol]]' is not assignable to type '(...args: any[]) => void'.
      Type 'Mutations<T>[Map[string]]' is not assignable to type '(...args: any[]) => void'.
        Type 'Mutations<T>[K]' is not assignable to type '(...args: any[]) => void'.
          Type 'Mutations<T>[OnlyString<Mutations<T>>]' is not assignable to type '(...args: any[]) => void'.
            Type 'Mutations<T>[string]' is not assignable to type '(...args: any[]) => void'.

150   >(k: Map): { [k in keyof Map]: Mutation<Mutations<T>[Map[k]]> };
                                              ~~~~~~~~~~~~~~~~~~~~

src/store.ts:155:30 - error TS2344: Type 'Mutations<T>[k]' does not satisfy the constraint '(...args: any[]) => void'.
  Type 'Mutations<T>[Keys]' is not assignable to type '(...args: any[]) => void'.
    Type 'Mutations<T>[OnlyString<Mutations<T>>]' is not assignable to type '(...args: any[]) => void'.

155   ): { [k in Keys]: Mutation<Mutations<T>[k]> };
                                 ~~~~~~~~~~~~~~~

src/store.ts:167:7 - error TS2344: Type 'GetNameSpaceObject<T, NameSpace, "mutations">[Map[k]]' does not satisfy the constraint '(...args: any[]) => void'.
  Type 'GetNameSpaceObject<T, NameSpace, "mutations">[Map[keyof Map]]' is not assignable to type '(...args: any[]) => void'.
    Type 'GetNameSpaceObject<T, NameSpace, "mutations">[Map[string]] | GetNameSpaceObject<T, NameSpace, "mutations">[Map[number]] | GetNameSpaceObject<...>[Map[symbol]]' is not assignable to type '(...args: any[]) => void'.
      Type 'GetNameSpaceObject<T, NameSpace, "mutations">[Map[string]]' is not assignable to type '(...args: any[]) => void'.
        Type 'GetNameSpaceObject<T, NameSpace, "mutations">[Keys]' is not assignable to type '(...args: any[]) => void'.
          Type 'GetNameSpaceObject<T, NameSpace, "mutations">[GetNameSpaceKeys<T, NameSpace, "mutations">]' is not assignable to type '(...args: any[]) => void'.
            Type 'GetNameSpaceObject<T, NameSpace, "mutations">[GetNameSpaceKeys<T, OnlyString<Module<T>>, "mutations">]' is not assignable to type '(...args: any[]) => void'.
              Type 'GetNameSpaceObject<T, NameSpace, "mutations">[GetNameSpaceKeys<T, string, "mutations">]' is not assignable to type '(...args: any[]) => void'.
                Type 'GetNameSpaceObject<T, NameSpace, "mutations">["mutations" extends OnlyString<Module<T>[keyof Module<T> & string]> ? OnlyString<...> : never]' is not assignable to type '(...args: any[]) => void'.
                  Type 'GetNameSpaceObject<T, NameSpace, "mutations">[OnlyString<Module<T>[keyof Module<T> & string][keyof Module<T>[keyof Module<...> & string] & "mutations"]>]' is not assignable to type '(...args: any[]) => void'.
                    Type 'GetNameSpaceObject<T, NameSpace, "mutations">[string]' is not assignable to type '(...args: any[]) => void'.
                      Type 'GetNameSpaceObject<T, OnlyString<Module<T>>, "mutations">[string]' is not assignable to type '(...args: any[]) => void'.
                        Type 'GetNameSpaceObject<T, string, "mutations">[string]' is not assignable to type '(...args: any[]) => void'.
                          Type '("mutations" extends OnlyString<Module<T>[keyof Module<T> & string]> ? Module<T>[keyof Module<T> & string][keyof Module<...>[keyof Module<...> & string] & "mutations"] : never)[string]' is not assignable to type '(...args: any[]) => void'.
                            Type 'Module<T>[keyof Module<T> & string][keyof Module<T>[keyof Module<T> & string] & "mutations"][string]' is not assignable to type '(...args: any[]) => void'.
                              Type 'Module<T>[keyof Module<T> & string]["mutations"][string]' is not assignable to type '(...args: any[]) => void'.
                                Type 'Module<T>[string]["mutations"][string]' is not assignable to type '(...args: any[]) => void'.

167       GetNameSpaceObject<T, NameSpace, 'mutations'>[Map[k]]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/store.ts:179:27 - error TS2344: Type 'GetNameSpaceObject<T, NameSpace, "mutations">[K]' does not satisfy the constraint '(...args: any[]) => void'.
  Type 'GetNameSpaceObject<T, NameSpace, "mutations">[Keys]' is not assignable to type '(...args: any[]) => void'.
    Type 'GetNameSpaceObject<T, NameSpace, "mutations">[GetNameSpaceKeys<T, NameSpace, "mutations">]' is not assignable to type '(...args: any[]) => void'.
      Type 'GetNameSpaceObject<T, NameSpace, "mutations">[GetNameSpaceKeys<T, OnlyString<Module<T>>, "mutations">]' is not assignable to type '(...args: any[]) => void'.
        Type 'GetNameSpaceObject<T, NameSpace, "mutations">[GetNameSpaceKeys<T, string, "mutations">]' is not assignable to type '(...args: any[]) => void'.
          Type 'GetNameSpaceObject<T, NameSpace, "mutations">["mutations" extends OnlyString<Module<T>[keyof Module<T> & string]> ? OnlyString<...> : never]' is not assignable to type '(...args: any[]) => void'.
            Type 'GetNameSpaceObject<T, NameSpace, "mutations">[OnlyString<Module<T>[keyof Module<T> & string][keyof Module<T>[keyof Module<...> & string] & "mutations"]>]' is not assignable to type '(...args: any[]) => void'.
              Type 'GetNameSpaceObject<T, NameSpace, "mutations">[string]' is not assignable to type '(...args: any[]) => void'.
                Type 'GetNameSpaceObject<T, OnlyString<Module<T>>, "mutations">[string]' is not assignable to type '(...args: any[]) => void'.

179     [K in Keys]: Mutation<GetNameSpaceObject<T, NameSpace, 'mutations'>[K]>;
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/test.ts:29:35 - error TS2344: Type 'Getters<T>[k]' does not satisfy the constraint '(...args: any) => any'.
  Type 'Getters<T>[Keys]' is not assignable to type '(...args: any) => any'.
    Type 'Getters<T>[keyof Getters<T>]' is not assignable to type '(...args: any) => any'.
      Type 'Getters<T>[string] | Getters<T>[number] | Getters<T>[symbol]' is not assignable to type '(...args: any) => any'.
        Type 'Getters<T>[string]' is not assignable to type '(...args: any) => any'.

29     [k in Keys]: () => ReturnType<Getters<T>[k]>
                                     ~~~~~~~~~~~~~


Found 9 errors in 2 files.

Errors  Files
     8  src/store.ts:63
     1  src/test.ts:29
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vuex-ts-enhance@0.0.7 build: `tsc -p .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the vuex-ts-enhance@0.0.7 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I tried to fix it by myself, but I failed.
there is my test code, do you have any advice?
thanks
```
import { StoreOptions } from 'vuex';
const module = {
  state: {
    name: '',
    age: 10,
  },
  getters: {
    getName(state) {
      return state.name;
    },
    getAge(state) {
      return state.age;
    }
  }
};

type Getters<T extends StoreOptions<any>> = T['getters'];
type StaticType = Getters<typeof module>;
type Keys = keyof StaticType;
type RT = ReturnType<StaticType[Keys]>;

abstract class MyClass<T extends StoreOptions<any>> {
  abstract mapGetters<Keys extends keyof Getters<T>>(k: Keys[]): {
    [k in Keys]: () => ReturnType<Getters<T>[k]> // <---------- shows type error here, no idea why it can't be recognized as 'Getter'
  }
}
```
![image](https://user-images.githubusercontent.com/18481891/170669749-b260d3d2-f016-4c3e-b8af-f4eaeb1c10d1.png)

**Comment by zWingz** [comment]
I think it is because `Getters` is optional, It may be `undefined`
<img width="560" alt="image" src="https://user-images.githubusercontent.com/13031838/181183438-89b338d5-1fd3-4443-aac5-b858739ed5e6.png">
<img width="861" alt="image" src="https://user-images.githubusercontent.com/13031838/181183653-1e1f3403-f718-4c71-b84e-16b5ed207ebe.png">

**Comment by zWingz** [comment]
fixed #31. released in `v0.0.9`
